### ISSUE TITLE
Translate

### ISSUE THREAD

**Issue by Coderbot4321** [TheCiROMG/dcs-codes-multiegg#1]
I am here asking if it would be okay for me to translate the messages to English.

**Comment by TheCiROMG** [comment]
@Coderbot4321 I will try to make the script in English, my main language is Spanish, but I can make some modifications, give me some time so I can translate everything completely.

**Comment by TheCiROMG** [comment]
@Coderbot4321 here this https://github.com/TheCiROMG/DCS-Codes-MultiMC-Egg/blob/main/egg-dcs-codes-multimc-egg-2-0-english.json
